# Build the in-process host: embeds the BEAM (beam.smp.dll, dynamically
# resolved) + the rext_nif render NIF into one native binary. Mirrors
# native/macos/host/build.sh's role — see decisions/2026-07-20-in-process-nif-
# host.md for the "why" and rext_host.c's header comment for what differs on
# Windows (no shipped import lib for erl_start -> LoadLibrary/GetProcAddress
# instead of static linking; beam.smp.dll is already self-contained, so there's
# no macOS-style separate erts_internal/ethread/pcre2/ryu linking to do).
#
# Requires gcc on PATH (MinGW-w64; `choco install mingw`).

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot
$here = $PSScriptRoot -replace '\\', '/'

$ErlRoot = if ($env:REXT_ERL_ROOT) { $env:REXT_ERL_ROOT } else { "C:/Program Files/erlang otp" }
$ErtsBin = if ($env:REXT_ERTS_BIN) { $env:REXT_ERTS_BIN } else { "$ErlRoot/erts-17.0.5/bin" }
$Boot = if ($env:REXT_BOOT) { $env:REXT_BOOT } else { "$ErlRoot/bin/start_clean" }
$ElixirEbin = if ($env:REXT_ELIXIR_EBIN) { $env:REXT_ELIXIR_EBIN } else { "C:/ProgramData/chocolatey/lib/elixir/tools/lib/elixir/ebin" }
$LoggerEbin = if ($env:REXT_LOGGER_EBIN) { $env:REXT_LOGGER_EBIN } else { "C:/ProgramData/chocolatey/lib/elixir/tools/lib/logger/ebin" }
$RextEbin = if ($env:REXT_EBIN) { $env:REXT_EBIN } else { ((Resolve-Path "$PSScriptRoot/../../../_build/dev/lib/rext/ebin").Path -replace '\\', '/') }
$NifPath = "$here/rext_nif"
$BeamDll = "$ErtsBin/beam.smp.dll"

Write-Output "ERL_ROOT:    $ErlRoot"
Write-Output "ERTS_BIN:    $ErtsBin"
Write-Output "REXT_EBIN:   $RextEbin"

# Generated header, not command-line -D defines: PowerShell's native-argv
# marshaling mangles embedded quotes (needed to turn a path into a C string
# literal) on the way to gcc — writing the macros straight to a file sidesteps
# shell quoting entirely.
$pathsHeader = @"
// Generated by build.ps1 — do not edit, do not commit.
#define REXT_ERL_ROOT "$ErlRoot"
#define REXT_ERTS_BIN "$ErtsBin"
#define REXT_BOOT "$Boot"
#define REXT_ELIXIR_EBIN "$ElixirEbin"
#define REXT_LOGGER_EBIN "$LoggerEbin"
#define REXT_EBIN "$RextEbin"
#define REXT_NIF_PATH "$NifPath"
#define REXT_BEAM_DLL "$BeamDll"
"@
Set-Content -Path "rext_paths.h" -Value $pathsHeader -Encoding ascii

# 1. Render NIF as a DLL. erl_nif.h's WinDynNifCallbacks table means enif_*
#    resolves via a function-pointer struct the emulator hands the NIF at
#    load time -- no import lib needed, unlike a normal Windows DLL dependency.
& gcc -shared -O2 -I"$ErtsBin/../include" -o rext_nif.dll rext_nif.c
if ($LASTEXITCODE -ne 0) { throw "gcc failed building rext_nif.dll" }
Write-Output "built: rext_nif.dll"

# 2. Host binary. erl_start is resolved at runtime (LoadLibrary/GetProcAddress
#    in rext_host.c), so this links against nothing beyond the standard CRT/
#    kernel32 -- no beam.smp.dll import lib, no erts_internal/ethread linking.
& gcc -O2 rext_host.c -o rext_host.exe
if ($LASTEXITCODE -ne 0) { throw "gcc failed building rext_host.exe" }

Write-Output "built: $PSScriptRoot\rext_host.exe"
Write-Output "run:   .\rext_host.exe    (boots embedded BEAM + rext app + NIF render path)"
