// rext_host — in-process host for the embedded BEAM (Windows).
//
// Mirrors native/macos/host/rext_host.c's architecture (see
// decisions/2026-07-20-in-process-nif-host.md for the "why"): the native
// binary owns the process, boots an embedded ERTS via `erl_start`, and the
// render backend is an in-process NIF (rext_nif) rather than a socket.
//
// Windows difference from macOS: there's no shipped import library for
// beam.smp.dll's `erl_start`, so it's resolved dynamically via
// LoadLibrary/GetProcAddress instead of being statically linked. That's also
// *simpler* than macOS's link step here — beam.smp.dll is a single
// self-contained DLL (pcre2/ryu already statically compiled in — see its
// export table), so there's no equivalent of macOS's separate
// liberts_internal_r.a/libethread.a/vendor pcre2+ryu linking to do.
//
// Headless, like the macOS host started out: boots the BEAM on the main
// thread and runs the rext app; render calls go through the NIF (which logs
// frames — see rext_nif.c for why the GUI hook doesn't port directly).
// Distribution stays on so an agent can drive it via Rext.Test.
//
// Paths come from rext_paths.h, generated by build.ps1 right before this
// compiles (a generated header sidesteps shell-quoting a path containing
// spaces and colons through a command-line -D define, which is what
// macOS's build.sh does — that route turned out to be genuinely fragile
// through PowerShell's native-argv marshaling).

#include <stdio.h>
#include <stdlib.h>
#include <windows.h>

#include "rext_paths.h"

typedef void (*erl_start_fn)(int, char **);
typedef void (*sys_primitive_init_fn)(HMODULE);

int main(void) {
    _putenv_s("ROOTDIR", REXT_ERL_ROOT);
    _putenv_s("BINDIR", REXT_ERTS_BIN);
    _putenv_s("PROGNAME", "erl");
    _putenv_s("EMU", "beam");
    _putenv_s("REXT_NIF_PATH", REXT_NIF_PATH);

    HMODULE beam = LoadLibraryA(REXT_BEAM_DLL);
    if (!beam) {
        fprintf(stderr, "[rext_host] LoadLibrary(%s) failed: %lu\n", REXT_BEAM_DLL, GetLastError());
        return 1;
    }

    erl_start_fn erl_start = (erl_start_fn)GetProcAddress(beam, "erl_start");
    if (!erl_start) {
        fprintf(stderr, "[rext_host] GetProcAddress(erl_start) failed: %lu\n", GetLastError());
        return 1;
    }

    // Must run before erl_start: sets the DLL's internal `beam_module` handle
    // so its own FindResource(beam_module, ..., "ERLANG_DICT"/"ERLANG_CODE")
    // calls resolve against beam.smp.dll's own resource section (where the
    // preloaded core modules live) instead of our host exe's. See
    // erts/emulator/sys/win32/sys.c upstream — sys_primitive_init/erl_start
    // are meant to be called by the same launcher in this order.
    sys_primitive_init_fn sys_primitive_init =
        (sys_primitive_init_fn)GetProcAddress(beam, "sys_primitive_init");
    if (!sys_primitive_init) {
        fprintf(stderr, "[rext_host] GetProcAddress(sys_primitive_init) failed: %lu\n", GetLastError());
        return 1;
    }
    sys_primitive_init(beam);

    const char *args[] = {"beam",
                          "--",
                          "-root",
                          REXT_ERL_ROOT,
                          "-bindir",
                          REXT_ERTS_BIN,
                          "-progname",
                          "erl",
                          "--",
                          "-boot",
                          REXT_BOOT,
                          "-pa",
                          REXT_ELIXIR_EBIN,
                          "-pa",
                          REXT_LOGGER_EBIN,
                          "-pa",
                          REXT_EBIN,
                          "-name",
                          "rext_host@127.0.0.1",
                          "-setcookie",
                          "rext_secret",
                          "-noshell",
                          "-noinput",
                          "-eval",
                          "'Elixir.Rext.Embedded':start().",
                          NULL};
    int ac = 0;
    while (args[ac])
        ac++;
    fprintf(stderr, "[rext_host] booting embedded BEAM (%d args)\n", ac);
    fflush(stderr);
    erl_start(ac, (char **)args);
    fprintf(stderr, "[rext_host] erl_start returned (unexpected)\n");
    return 0;
}
